### ISSUE TITLE
Cassettes

### ISSUE THREAD

**Issue by RoxasShadow** [mozestudio/zanox-rb#10]
Considering that we do actual HTTP requests to Zanox inside our tests, probably could be a good idea using [VCR](https://github.com/vcr/vcr) so that tests would pass fine. We would lose the certainty that the gem works fine against the changes by Zanox on their APIs but I honestly doubt about the possibility of that to happen.

WDYT @desmondhume?

**Comment by desmondhume** [comment]
I absolutely agree. I don't think we'll have breaking changes for a while, so it's 99% safe to use cassettes for testing 👍  
I'll start "recording" some cassettes as soon as possibile, but PRs are more than welcome 😸

**Comment by RoxasShadow** [comment]
I didn't have a chance to try it yet, but #11 could be a good starting point.

**Comment by RoxasShadow** [comment]
Merged at c90857f507e8bd123cc0e7371b1ef345eb362def, closing this.
